config/routes.rb
CaceoCosts::Application.routes.draw do

  get 'reports/progress',   to: 'reports#progress',  as: 'progress_report'
  get 'reports/responses',  to: 'reports#responses', as: 'responses_report'
  resources :elections do
    resources :surveys
  end  

  resources :survey_responses

  # json
  resources :workshops,       only: [:index]
  resources :questions,       only: [:index]
  resources :response_values, only: [:index]
  resources :counties,        only: [:index]
  resources :surveys,         only: [:index]

  resources :data, only: [:index]
  resources :progress, only: [:index, :show]

  resources :faqs
  resources :announcements
  resources :password_resets
  resources :election_technologies

  get 'activities', to: 'activities#index'
  get 'activities/summary', to: 'activities#summary', as: 'activity_summary'
  get 'activities/earlier', to: 'activities#earlier', as: 'activity_earlier'


  resources :tech_voting_machines do
    get "delete"
  end

  resources :tech_voting_softwares do
    get "delete"
  end

  root :to => "users#login"
  get "signup", to: "users#new" ,    as: "signup"
  get "login" , to: "users#login",   as: "login"
  get "logout", to: "users#logout",  as: "logout"
  get  "forgot_password" => "users#forgot_password",   as: "forgot_password"
  post "reset_password"  => "users#reset_password",    as: "reset_password"
  post "login_attempt", to: "users#login_attempt"
  resources :users
  resources :user_steps
  resources :users do
    get   :profile,           :on => :member, as: "profile"
    get   :securityquestion,  :on => :member
    post  :securityquestion_submit, :on => :member
    get   :update_password,         :on => :member
    post  :updatepassword_submit ,  :on => :member
  end
resources :messages, only: [:new, :create]

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  default_scope { order( created_at: :desc ) }

  def viewed_by?(user)
    if !user.announcements_viewed_at
      false
    else
      self.created_at <= user.announcements_viewed_at
    end
  end

  def self.count_new_for(user)
    if user.announcements_viewed_at
      Announcement.where("created_at > ?", user.announcements_viewed_at).count
    else
      Announcement.count
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  after_filter :touch_viewed_at, only: :index

  def index
    @last_viewed = current_user.announcements_viewed_at
    @announcements = Announcement.all
  end

  def new
    @announcement = Announcement.new
    @announcements = Announcement.all
  end

  def create
    @announcement = Announcement.new(announcement_params)
    if @announcement.save
      redirect_to action: :index
    else
      flash.now[:error] = 'Could not save announcement'
      render :new
    end
  end

  def destroy
    Announcement.destroy(params[:id])
    redirect_to announcements_url
  end

  private
  def touch_viewed_at
    current_user.touch(:announcements_viewed_at)
  end

  def announcement_params
    params.require(:announcement).permit(:message, :id)
  end
end

app/views/announcements/_announcement.html.erb
<div class="row announcement-row">
  <div class="col-sm-1 col-xs-2"><%= render "new_badge" unless announcement.viewed_by?(current_user) %></div>
  <div class="col-sm-1 col-xs-3"><%= announcement.created_at.strftime('%m/%d/%Y') %></div>
  <span class="col-sm-8 col-xs-5"><%= announcement.message %></span>
  <% if allow? :announcements, :destroy %>
    <div class="col-sm-1 col-xs-2">
      <%= link_to 'delete', announcement, {method: :delete,  data: {confirm:"Are you sure?"}, class: 'btn btn-default'} %>
    </div>
  <% end %>
</div>

app/views/announcements/_new_badge.html.erb
<span class="badge"> New! </span>

app/views/announcements/index.html.erb
<div class="row">
  <div class="col-xs-5 col-xs-offset-1">
    <h1>Announcements</h1>
    <% if allow? :announcements, :new %>
      <span> 
        <%= link_to 'Create a new announcement', new_announcement_path, {class: 'btn btn-default announcement-row'} %>
      </span>
    <% end %>
  </div>
</div>

<%= render partial: 'announcement', collection: @announcements %>

app/views/announcements/new.html.erb
<div class="row">
  <h1 class="col-sm-5 col-sm-offset-1">Announcements</h1>
</div>
<div class="row">
  <div class="col-sm-5 col-sm-offset-1">
    <%= form_for @announcement do |f| %>
      <%= f.text_area :message, rows:5, cols:100 %>
      <%= f.submit "Create", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<%= render partial: 'announcement', collection: @announcements %>