config/routes.rb
CaceoCosts::Application.routes.draw do

  get 'reports/progress',   to: 'reports#progress',  as: 'progress_report'
  get 'reports/responses',  to: 'reports#responses', as: 'responses_report'
  resources :elections do
    resources :surveys
  end  

  resources :survey_responses

  # json
  resources :workshops,       only: [:index]
  resources :questions,       only: [:index]
  resources :response_values, only: [:index]
  resources :counties,        only: [:index]
  resources :surveys,         only: [:index]

  resources :data, only: [:index]
  resources :progress, only: [:index, :show]

  resources :faqs
  resources :announcements
  resources :password_resets
  resources :election_technologies

  get 'activities', to: 'activities#index'
  get 'activities/summary', to: 'activities#summary', as: 'activity_summary'
  get 'activities/earlier', to: 'activities#earlier', as: 'activity_earlier'


  resources :tech_voting_machines do
    get "delete"
  end

  resources :tech_voting_softwares do
    get "delete"
  end

  root :to => "users#login"
  get "signup", to: "users#new" ,    as: "signup"
  get "login" , to: "users#login",   as: "login"
  get "logout", to: "users#logout",  as: "logout"
  get  "forgot_password" => "users#forgot_password",   as: "forgot_password"
  post "reset_password"  => "users#reset_password",    as: "reset_password"
  post "login_attempt", to: "users#login_attempt"
  resources :users
  resources :user_steps
  resources :users do
    get   :profile,           :on => :member, as: "profile"
    get   :securityquestion,  :on => :member
    post  :securityquestion_submit, :on => :member
    get   :update_password,         :on => :member
    post  :updatepassword_submit ,  :on => :member
  end
resources :messages, only: [:new, :create]

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  default_scope { order(created_at: :asc) }
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  # def show
  # end

  # GET /faqs/new
  def new
    @faq = Faq.new
    @faqs = Faq.all
  end

  # GET /faqs/1/edit
  def edit
    @faqs = Faq.all
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to faqs_url, notice: 'Q/A was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to faqs_url, notice: 'Faq was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/views/faqs/_faq.html.erb
<div class="faq-item">
  <div class="row">
    <span class="col-sm-9 col-xs-5 col-xs-offset-1"><strong>Q:</strong> <%= faq.question %></span>
    <span class="col-sm-9 col-xs-5 col-xs-offset-1"><strong>A:</strong> <%= faq.answer %></span>
    <% if allow? :faqs, :edit %>
      <div class="col-sm-1 col-xs-2">
        <%= link_to 'Edit', edit_faq_path(faq), class: 'btn btn-default' %>
      </div>
    <% end %>
    <% if allow? :faqs, :destroy %>
      <div class="col-sm-1 col-xs-2">
        <%= link_to 'Delete', faq, {method: :delete,  data: {confirm:"Are you sure?"}, class: 'btn btn-default'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/faqs/_form.html.erb
<div class="row faq-form">
  <div class="col-xs-11 col-xs-offset-1">
    <%= simple_form_for @faq do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <p>Question</p>
        <%= f.text_area :question, rows:5, cols:100 %>
        <p>Answer</p>
        <%= f.text_area :answer, rows:5, cols:100 %>
      </div>
      <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/faqs/_title.html.erb
<div class="row">
  <div class="col-xs-11 col-xs-offset-1">
    <h1>Frequently Asked Questions</h1>
  </div>
</div>

app/views/faqs/edit.html.erb
<%= render 'title' %>

<%= render 'form' %>

<%= render partial: 'faq', collection: @faqs %>
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<%= render 'title' %>

<div class="row">
  <div class="col-xs-11 col-xs-offset-1">
    <% if allow? :faqs, :new %>
      <span> 
        <%= link_to 'Create a new Q/A', new_faq_path, {class: 'btn btn-default announcement-row'} %>
      </span>
    <% end %>
  </div>
</div>

<%= render partial: 'faq', collection: @faqs %>

app/views/faqs/new.html.erb
<%= render 'title' %>

<%= render 'form' %>

<%= render partial: 'faq', collection: @faqs %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>