config/routes.rb
CaceoCosts::Application.routes.draw do

  get 'reports/progress',   to: 'reports#progress',  as: 'progress_report'
  get 'reports/responses',  to: 'reports#responses', as: 'responses_report'
  resources :elections do
    resources :surveys
  end  

  resources :survey_responses

  # json
  resources :workshops,       only: [:index]
  resources :questions,       only: [:index]
  resources :response_values, only: [:index]
  resources :counties,        only: [:index]
  resources :surveys,         only: [:index]

  resources :data, only: [:index]
  resources :progress, only: [:index, :show]

  resources :faqs
  resources :announcements
  resources :password_resets
  resources :election_technologies

  get 'activities', to: 'activities#index'
  get 'activities/summary', to: 'activities#summary', as: 'activity_summary'
  get 'activities/earlier', to: 'activities#earlier', as: 'activity_earlier'


  resources :tech_voting_machines do
    get "delete"
  end

  resources :tech_voting_softwares do
    get "delete"
  end

  root :to => "users#login"
  get "signup", to: "users#new" ,    as: "signup"
  get "login" , to: "users#login",   as: "login"
  get "logout", to: "users#logout",  as: "logout"
  get  "forgot_password" => "users#forgot_password",   as: "forgot_password"
  post "reset_password"  => "users#reset_password",    as: "reset_password"
  post "login_attempt", to: "users#login_attempt"
  resources :users
  resources :user_steps
  resources :users do
    get   :profile,           :on => :member, as: "profile"
    get   :securityquestion,  :on => :member
    post  :securityquestion_submit, :on => :member
    get   :update_password,         :on => :member
    post  :updatepassword_submit ,  :on => :member
  end
resources :messages, only: [:new, :create]

end

app/models/tech_voting_software.rb
class TechVotingSoftware < ActiveRecord::Base
  include TechResponseable

  def self.title
    'Tabulation and Other Equipment Purchases'
  end

  def self.id
    self.to_s
  end

  def self.descriptions
    {
      'software_item' => 'Tabulation and Other Equipment Type',
      'purchase_dt'   => 'Purchase Date',
      'purchase_price_hardware' => 'Hardware Purchase Price',
      'purchase_price_software' => 'Software Purchase Price',
      'mat_charges' => 'Annual Maintenance Charges For Software',
      'labor_costs' => 'Average Annual Labor Costs',
    }
  end
end

app/controllers/tech_voting_softwares_controller.rb
class TechVotingSoftwaresController < ApplicationController
  before_action :set_tech_voting_software, only: [:show, :edit, :update, :destroy]
  before_action :get_user

  # GET /tech_voting_machines
  # GET /tech_voting_machines.json
  def index
    @county_name  = County.where(id: @user[:county_id]).pluck(:name)
    @tech_voting_softwares = TechVotingSoftware.where(county_id: @user[:county_id])
  end

  # GET /tech_voting_machines/1
  # GET /tech_voting_machines/1.json
  def show
    @tech_voting_software = TechVotingSoftware.find(params[:id])
  end

  # GET /tech_voting_machines/new
  def new
    @tech_voting_software = TechVotingSoftware.new
  end

  # GET /tech_voting_machines/1/edit
  def edit
    @tech_voting_software = TechVotingSoftware.find(params[:id])
  end

  # POST /tech_voting_machines
  # POST /tech_voting_machines.json
  def create
    @tech_voting_softwares = TechVotingSoftware.where(county_id: @user[:county_id])
    @tech_voting_software = TechVotingSoftware.create(tech_voting_software_params)
  end

  # PATCH/PUT /tech_voting_machines/1
  # PATCH/PUT /tech_voting_machines/1.json
  def update
    @tech_voting_softwares = TechVotingSoftware.where(county_id: @user[:county_id])
    @tech_voting_software.update(tech_voting_software_params)
  end

 def delete
    @tech_voting_software =  TechVotingSoftware.find(params[:tech_voting_software_id])
  end

  def destroy
    @tech_voting_softwares = TechVotingSoftware.where(county_id: @user[:county_id])
    @tech_voting_software = TechVotingSoftware.find(params[:id])
    @tech_voting_software.destroy
  end

private
  # for some reason delete has its id in params[tech_voting_machine_id]
  def current_resource
    @current_resource ||= if params[:id]
      TechVotingSoftware.find(params[:id])
    elsif params[:tech_voting_software_id]
      TechVotingSoftware.find(params[:tech_voting_software_id])
    else
      params['tech_voting_software']
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_tech_voting_software
    @tech_voting_software = TechVotingSoftware.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tech_voting_software_params
    params.require(:tech_voting_software).permit(:county_id, :software_item, :purchase_dt, :purchase_price_hardware, :purchase_price_software, :quantity, :mat_charges, :labor_costs)
  end
end

app/views/tech_voting_softwares/_delete.html.erb
<div class="modal-header">
  <h3>Delete Tabulation and Other Equipment Purchase</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @tech_voting_software.software_item %></b>?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This Item",  tech_voting_software_path(@tech_voting_software), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Cancel This Action", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/tech_voting_softwares/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@tech_voting_software.software_item}" %></h3>
</div>
<%= render "form" %>

app/views/tech_voting_softwares/_form.html.erb
<%= form_for @tech_voting_software, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :software_item, 'Tabulation and other Equipment <span align="left"  style="font-size: 9px"> (EX: GIS/Mapping software) <span>'.html_safe,  class:"control-label" %>
      <div class="controls">
        <%= f.text_field :software_item %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :purchase_dt, 'Purchase Date', class: "control-label" %>
      <div class="controls">
        <%= f.date_field :purchase_dt %>
      </div>
    </div>

     <div class="control-group">
      <%= f.label :purchase_price_hardware, 'Hardware Purchase Price',  class:"control-label" %>
      <div class="controls">
        <%= f.number_field :purchase_price_hardware %>
      </div>
    </div>


     <div class="control-group">
      <%= f.label :purchase_price_software, 'Software Purchase Price',  class:"control-label" %>
      <div class="controls">
        <%= f.number_field :purchase_price_software %>
      </div>
    </div>


     <div class="control-group">
      <%= f.label :mat_charges, 'Ongoing Annual Maintenance Charges for Software',  class:"control-label" %>
      <div class="controls">
        <%= f.number_field :mat_charges %>
      </div>
    </div>


     <div class="control-group">
      <%= f.label :labor_costs, 'Average Annual Labor Costs <span align="left"  style="font-size: 9px"> (non redistricting years)</span>'.html_safe,  class:"control-label" %>
      <div class="controls">
        <%= f.number_field :labor_costs%>
      </div>
    </div>


    <%=  f.hidden_field :county_id,  :value =>  @user[:county_id] %>



  </div>
  <div class="modal-footer">
    <%= f.submit  "Save", class: "btn" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/tech_voting_softwares/_index.html.erb
<% @tech_voting_softwares.each do |tech_voting_software| %>
  <tr>
    <td><%= tech_voting_software.software_item  %></td>
    <td><%= tech_voting_software.purchase_dt    %></td>
    <td><%= tech_voting_software.purchase_price_hardware  %></td>
    <td><%= tech_voting_software.purchase_price_software  %></td>
    <td><%= tech_voting_software.mat_charges  %></td>
    <td><%= tech_voting_software.labor_costs  %></td>

    <td><%= link_to "Edit", edit_tech_voting_software_path(tech_voting_software), remote: true, class: "btn" %></td>
    <td><%= link_to "Delete", tech_voting_software_delete_path(tech_voting_software), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/tech_voting_softwares/_new.html.erb
<div class="modal-header">
<h2 class ="myh2yr">Please Tell Us About Your Tabulation and Other Equipment Purchases Since 2003</h2>

</div>
<%= render "form" %>

app/views/tech_voting_softwares/_save.js.erb
$("ul.errors").html("")
<% if @tech_voting_software.errors.any? %>
  <% @tech_voting_software.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".tech-index").html("<%= escape_javascript(render 'index') %>")
  $("#tech-modal").modal("hide")
<% end %>

app/views/tech_voting_softwares/create.js.erb
<%= render "save" %>

app/views/tech_voting_softwares/delete.js.erb
$("#tech-modal-inner").html("<%= escape_javascript(render 'delete') %>")
$("#tech-modal").modal("show")

app/views/tech_voting_softwares/destroy.js.erb
<%= render "save" %>

app/views/tech_voting_softwares/edit.js.erb
$("#tech-modal-inner").html("<%= escape_javascript(render 'edit') %>")
$("#tech-modal").modal("show")

app/views/tech_voting_softwares/index.html.erb
<h2 class ="myh2yr">Tabulation and Other Equipment Purchases Since 2003 for <%= @county_name[0] %></h2>


<div class="container">
  <div class="well">
    <%=link_to ' New Tabulation or Other Equipment Item', new_tech_voting_software_path, remote: true, class: "btn btn-i icon-arrow-right"%>
  </div>
  <div class="new-tech"></div>

  <table class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Tabulation and Other Equipment Type</th>
        <th>Purchase Date</th>
         <th> Hardware Purchase Price</th>
        <th> Software Purchase Price</th>
            <th>Annual Maintenance Charges For Software</th>
            <th>Average Annual Labor Costs</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="tech-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div class="end_link_tech">
<%= link_to "Election Technology Home", election_technologies_path  %>
</div>


<div class="modal fade" id="tech-modal">
  <div class="modal-dialog">
    <div id="inner-product-modal" class="modal-content">
      <div id="tech-modal-inner"></div>
    </div>
  </div>
</div>

app/views/tech_voting_softwares/new.js.erb
$("#tech-modal-inner").html("<%= escape_javascript(render 'new') %>")
$("#tech-modal").modal("show")

app/views/tech_voting_softwares/update.js.erb
<%= render "save" %>