config/routes.rb
CaceoCosts::Application.routes.draw do

  get 'reports/progress',   to: 'reports#progress',  as: 'progress_report'
  get 'reports/responses',  to: 'reports#responses', as: 'responses_report'
  resources :elections do
    resources :surveys
  end  

  resources :survey_responses

  # json
  resources :workshops,       only: [:index]
  resources :questions,       only: [:index]
  resources :response_values, only: [:index]
  resources :counties,        only: [:index]
  resources :surveys,         only: [:index]

  resources :data, only: [:index]
  resources :progress, only: [:index, :show]

  resources :faqs
  resources :announcements
  resources :password_resets
  resources :election_technologies

  get 'activities', to: 'activities#index'
  get 'activities/summary', to: 'activities#summary', as: 'activity_summary'
  get 'activities/earlier', to: 'activities#earlier', as: 'activity_earlier'


  resources :tech_voting_machines do
    get "delete"
  end

  resources :tech_voting_softwares do
    get "delete"
  end

  root :to => "users#login"
  get "signup", to: "users#new" ,    as: "signup"
  get "login" , to: "users#login",   as: "login"
  get "logout", to: "users#logout",  as: "logout"
  get  "forgot_password" => "users#forgot_password",   as: "forgot_password"
  post "reset_password"  => "users#reset_password",    as: "reset_password"
  post "login_attempt", to: "users#login_attempt"
  resources :users
  resources :user_steps
  resources :users do
    get   :profile,           :on => :member, as: "profile"
    get   :securityquestion,  :on => :member
    post  :securityquestion_submit, :on => :member
    get   :update_password,         :on => :member
    post  :updatepassword_submit ,  :on => :member
  end
resources :messages, only: [:new, :create]

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :survey_responses, inverse_of: :survey, foreign_key: :response_type
  has_many :questions, inverse_of: :survey
  has_many :ssvehs,   through: :survey_responses, source: :response, source_type: 'Ssveh'
  has_many :salvbms,  through: :survey_responses, source: :response, source_type: 'Salvbm'
  has_many :salbals,  through: :survey_responses, source: :response, source_type: 'Salbal'
  has_many :salpps,   through: :survey_responses, source: :response, source_type: 'Salpp'
  has_many :salpws,   through: :survey_responses, source: :response, source_type: 'Salpw'
  has_many :salmeds,  through: :survey_responses, source: :response, source_type: 'Salmed'
  has_many :saldojos, through: :survey_responses, source: :response, source_type: 'Saldojo'
  has_many :salcans,  through: :survey_responses, source: :response, source_type: 'Salcan'
  has_many :salbcs,   through: :survey_responses, source: :response, source_type: 'Salbc'
  has_many :saloths,  through: :survey_responses, source: :response, source_type: 'Saloth'
  has_many :postages, through: :survey_responses, source: :response, source_type: 'Postage'
  has_many :sspps,    through: :survey_responses, source: :response, source_type: 'Sspp'
  has_many :sspws,    through: :survey_responses, source: :response, source_type: 'Sspw'
  has_many :ssoths,   through: :survey_responses, source: :response, source_type: 'Ssoth'
  has_many :ssmeds,   through: :survey_responses, source: :response, source_type: 'Ssmed'
  has_many :sscans,   through: :survey_responses, source: :response, source_type: 'Sscan'
  has_many :ssbals,   through: :survey_responses, source: :response, source_type: 'Ssbal'
  has_many :ssbcs,    through: :survey_responses, source: :response, source_type: 'Ssbc'
  has_many :election_profiles, through: :survey_responses, source: :response, source_type: 'ElectionProfile'
  has_and_belongs_to_many :subsections, join_table: "survey_subsections", class_name: 'Subsection'
  has_and_belongs_to_many :totals_subsections, join_table: "survey_totals_subsections", class_name: 'Subsection'
  default_scope { order(category: :asc, title: :asc) }

  self.primary_key = :id

  LABEL = {
    "ElectionProfile" => "Election Profile",
    "Saloth" => "SAL Other",
    "Salbc" => "SAL Ballot Counting",
    "Salcan" => "SAL Candidates",
    "Saldojo" => "SAL DOJ Stakeholders",
    "Salmed" => "SAL Media",
    "Salpw" => "SAL Poll Workers",
    "Salpp" => "SAL Polling Places",
    "Salbal" => "SAL Ballots",
    "Salvbm" => "SAL VBM",
    "Ssbc" => "S&S Ballot Counting",
    "Ssbal" => "S&S Ballot Printing",
    "Sscan" => "S&S Candidate",
    "Ssmed" => "S&S Media",
    "Ssoth" => "S&S Other",
    "Sspw" => "S&S Poll Worker",
    "Sspp" => "S&S Polling Place",
    "Postage" => "S&S Postage",
    "Ssveh" => "S&S Vehicle"
  }

  def label
    LABEL[id]
  end

  def responses
    send table_name
  end

  def subsections
    Subsection.where(id: questions.pluck(:subsection_id).uniq)
  end

  def election_profile?
    category == "Election Profile" ? true : false
  end

  def salary?
    category == "Salaries" ? true : false
  end

  def service_supply?
    category == "Services and Supplies" ? true : false
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    respond_to do |format|
      format.json { render json: Survey.all }
      format.html do
        @election = Election.find(params[:election_id])
        @srs = SurveyResponse.where(
          county: current_user.county,
          election_id: params[:election_id]
        )
        session[:election_id] = params[:election_id]

        @salary_surveys = Survey.where(category: "Salaries")
        @salary_srs = SurveyResponse.where(response_type: @salary_surveys.pluck(:id), 
          county: current_user.county,
          election_id: params[:election_id])
        @salary_total = @salary_srs.total
        @salary_hash = @salary_surveys.map do |survey|
          sr = @salary_srs.detect { |sr| sr.response_type == survey.id }
          {survey: survey, survey_response: sr }
        end

        @supply_surveys = Survey.where(category: "Services and Supplies")
        @supply_srs = SurveyResponse.where(response_type: @supply_surveys.pluck(:id), 
          county: current_user.county,
          election_id: params[:election_id])
        @supply_total = @supply_srs.total
        @supply_hash = @supply_surveys.map do |survey|
          sr = @supply_srs.detect { |sr| sr.response_type == survey.id }
          {survey: survey, survey_response: sr }
        end

        @ep_sr = SurveyResponse.find_by(response_type: 'ElectionProfile',
          county: current_user.county,
          election_id: params[:election_id])
        @ep_hash = [{ survey: Survey.find('ElectionProfile'), survey_response: @ep_sr ? @ep_sr : nil }]
      end
    end
  end
end

app/views/surveys/_hint_annotation.html.erb
<div class="modal fade" id="<%= hint_annotation.field %>_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <h3><%= hint_annotation.label.titleize %></h3>
      </div>

      <div class="modal-body">
        <p><%= hint_annotation.description %></p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_status.html.erb
<% if status[:survey_response] == nil %>
  <% url = new_survey_response_path(
    election_id: params[:election_id], 
    county_id: current_user.county_id, 
    survey_id: status[:survey].id
    ) %>
<% else %>
  <% total = status[:survey_response].total %>
  <% percent = status[:survey_response].percent_complete %>
  <% url = survey_response_path( status[:survey_response].id ) %>
<% end %>

<div class="row">
  <div class="survey-index-title">
    <span><%= link_to( status[:survey].title, url ) %></span>
  </div>

  <div class="survey-index-progress">
    <div class="progress">
      <% unless status[:survey_response] == nil %>
        <div class="progress-bar" role="progressbar" aria-valuenow=<%="#{percent}"%> aria-valuemin="0" aria-valuemax="100" style="<%="width: #{percent}%;" %>">
          <%= percent ? "#{percent}%" : '' %></div>
      <% end %>
    </div>
  </div>

  <% unless status[:survey].id == 'ElectionProfile' %>
    <div class="survey-index-total">
      <%= total ? "$#{number_with_delimiter total}" : 'Not Started'%>
    </div>
  <% end %>
</div>

app/views/surveys/_survey_status_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <h3 class="survey-index-title"><%= survey_hash[0][:survey].category %></h3>
      <h3 class="survey-index-progress">Progress Completing Survey</h3>
      <h3 class="survey-index-total">
        <% unless survey_hash[0][:survey].id == 'ElectionProfile' %>
          Totals
        <% end %>
      </h3>
<!--       < class="survey-index-na"></h3>
 -->    
    </div>
  </div>
  <div class="panel-body">
    <%= render partial: 'status', collection: survey_hash %>
  </div>

  <% if panel_total %> 
    <div class="panel-footer">
      <div class="row">
        <div class="survey-index-title show_item_title_total">Total Costs</div>
        <div class="survey-index-progress"></div>
        <div class="survey-index-total show_item_total">$<%=number_with_delimiter panel_total %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/surveys/index.html.erb
<H2 class="myh2cats"> <%= "Survey Summary for the " + @election.name %> </H2>
<h2><small>Click on a Survey to Begin</small></h2>

<%= render partial: 'survey_status_panel', locals: { panel_total: @salary_total, survey_hash: @salary_hash } %>
<%= render partial: 'survey_status_panel', locals: { panel_total: @supply_total, survey_hash: @supply_hash } %>
<%= render partial: 'survey_status_panel', locals: { panel_total: nil, survey_hash: @ep_hash } %>

<h3 class="col-sm-9">Total Direct Costs for the <%= @election.name.titleize %></h3>
<h3 class="survey-index-total">$<%= number_with_delimiter( @srs.total ) %></h3>

<div class="category_break"></div>
<div class="category_end_link"><%= link_to "All Elections", elections_path  %></div>